services:
    _defaults:
        autowire: true
        autoconfigure: true

    TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZBinaryFileValidator:
        class: TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZBinaryFileValidator
        public: true

    TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZImageFileValidator:
        class: TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZImageFileValidator
        public: true

    TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZMediaValidator:
        class: TanoConsulting\eZDBIntegrityBundle\Constraints\Database\eZMediaValidator
        public: true

    TanoConsulting\eZDBIntegrityBundle\Constraints\Filesystem\eZBinaryFileAndMediaValidator:
        class: TanoConsulting\eZDBIntegrityBundle\Constraints\Filesystem\eZBinaryFileAndMediaValidator
        public: true

    TanoConsulting\eZDBIntegrityBundle\Constraints\Filesystem\eZImageFileValidator:
        class: TanoConsulting\eZDBIntegrityBundle\Constraints\Filesystem\eZImageFileValidator
        public: true
